### ISSUE TITLE
When ENABLE_LIMITED_CACHE : 'true' secret-resolver doesnt work as expected

### ISSUE THREAD

**Issue by PK85** [SAP/sap-btp-service-operator#450] opened 2024-07-09 08:59 UTC
We deployed v0.6.5 and with ENABLE_LIMITED_CACHE: "false" everything is ok. When we switched to ENABLE_LIMITED_CACHE: "true" the controller only works with secret from managedNamespace, it doesnt use "sap-btp-service-operator" secrets from user namespaces.

**Comment by kerenlahav** [comment] 2024-07-11 08:06
Hi Pioter,
I was able to reproduce the issue, but I could not find any solution for retrieving secrets that don't have the required label  (services.cloud.sap.com/managed-by-sap-btp-operator: "true"), this is the kuberenetes behavior, adding this label to the secret is solving the issue - tested successfully (updating the secret with the label does not require restart of the operator).
Since these secret are created by the user and not by the btp operator we cannot migrate them to include the required label automatically, if a customer uses this feature he must update the secret he created with the label.
Currently the limited cache feature is not documented, we'll make sure to include it in the documentation.

Another solution might be to limit the allowed namespaces (ENABLE_CLUSTER_ACCESS=false), this will not require any change of the secrets but will limit the operator only for pre defined namespaces.

**Comment by kerenlahav** [comment] 2024-07-11 09:38
**UPDATE** 
@evyaffe suggested to use uncached client as a fallback in case secret is not found in cached client
will be tested and merged if ok

**Comment by PK85** [comment] 2024-07-11 09:44
I like your update last comment. If not exist in cache, use uncached client and search for secrets all existing rules.

**Comment by PK85** [comment] 2024-07-11 09:46
@kerenlahav  Question, right now when ENABLE_LIMITED_CACHE: "true" which secrets do you label to be included in the cache? All from managed namespace, of just default one from managed namespace?

**Comment by kerenlahav** [comment] 2024-07-11 09:48
just the one created by helm

**Comment by kerenlahav** [comment] 2024-07-18 16:05
Hi @PK85 
please check fix in https://github.com/SAP/sap-btp-service-operator/releases/tag/v0.6.6

**Closed** 2024-08-05 05:56 UTC
